Repository Brooklyn-STEAM/10045-Simplifying-the-College-Search-Process-Through-Digestible-Data, pull requests merged in 2025-05, with the labels that each got.

#106 Sprint 7 remaster
  README.md
  main.py
  static/styles/style.css
  templates/browse.html.jinja
  templates/components/flashes.html.jinja
  templates/components/footer.html.jinja
  templates/components/navbar.html.jinja
  templates/credits.html.jinja
  templates/homepage.html.jinja
  templates/settings.html.jinja
  templates/sign_in.html.jinja
Labels: merge conflict, Frontend, Backend

#107 10045 204 hide empty pages on pagnation
  main.py
  templates/browse.html.jinja
  templates/components/pagination.html.jinja
Labels: merge conflict, Backend

#108 218 - Add clear form buttons
  templates/browse.html.jinja
  templates/homepage.html.jinja
  templates/settings.html.jinja
  templates/sign_in.html.jinja
Labels: Frontend
